"""player.nickname citext

Revision ID: 4bdcd2511081
Revises: 19f4261ee339
Create Date: 2025-07-23 00:33:16.761716

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4bdcd2511081"
down_revision: Union[str, Sequence[str], None] = "19f4261ee339"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "player",
        "nickname",
        existing_type=sa.VARCHAR(length=32),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_player_nickname"), "player", type_="unique")
    op.drop_index(op.f("ix_player_nickname"), table_name="player")
    op.create_index(op.f("ix_player_nickname"), "player", ["nickname"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_nickname"), table_name="player")
    op.create_index(op.f("ix_player_nickname"), "player", ["nickname"], unique=False)
    op.create_unique_constraint(
        op.f("uq_player_nickname"),
        "player",
        ["nickname"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "player",
        "nickname",
        existing_type=postgresql.CITEXT(),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
