"""init

Revision ID: d5e237dd6d63
Revises: 
Create Date: 2025-07-15 19:05:15.331083

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d5e237dd6d63"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
